name: Deploy MultiDocker
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      # Specify Docker as dependency
      - run: docker login -u ${{ secrets.DOCKER_USERNAME}} -p ${{ secrets.DOCKER_PASSWORD }}
      
      # Build test version of React project (can easily add other services here)
      - run: docker build -t cygnetops/react-test -f ./client/Dockerfile.dev ./client
      
      # Run tests on React project test version (can easily add other services here)
      - run: docker run -e CI=true cygnetops/react-test npm test
      
      # Build Prod versions of all of our projects if tests pass
      - run: docker build -t miller222111/multi-client-10-14 ./client
      - run: docker build -t miller222111/multi-nginx-10-14 ./nginx
      - run: docker build -t miller222111/multi-server-10-14 ./server
      - run: docker build -t miller222111/multi-worker-10-14 ./worker

      # Push all services/projects Images to Docker Hub
      - run: docker push miller222111/multi-client-10-14
      - run: docker push miller222111/multi-nginx-10-14
      - run: docker push miller222111/multi-server-10-14
      - run: docker push miller222111/multi-worker-10-14